var wtf = new Audio("sound/WTF.mp3");
var mada = new Audio("sound/mada.mp3");
var healing = new Audio("sound/INeedHealing.mp3");
var gay = new Audio("sound/ImGay.mp3");
var omaewamu = new Audio("sound/Omaewamu.mp3");
var depression = new Audio("sound/IHaveCripplingDepression.mp3");
var asteoporosis = new Audio("sound/IHaveAsteoporosis.mp3");
var die = new Audio("sound/IWantToDie.mp3");
var slow = new Audio("sound/EveryoneIsSlow.mp3");
var running = new Audio("sound/WhyAreYouRunning.mp3");
var easy = new Audio("sound/easy.mp3");
var nico = new Audio("sound/NicoNicoNii.mp3");
var dance = new Audio("sound/DanceTillYoureDead.mp3");
var computer = new Audio("sound/WhatAreYouDoingOnComputer.mp3");
var cena = new Audio("sound/JohnCena.mp3");
var rusure = new Audio("sound/AreYouSure.mp3");
var bobtriggered = new Audio("sound/SpongeBobTriggered.mp3");
var headshot = new Audio("sound/boom_headshot.mp3");
var normies = new Audio("sound/FuckingNormies.mp3");
var minecraft = new Audio("sound/ImPlayingMinecraft.mp3");
var dead = new Audio("sound/imdead.mp3");
var mark = new Audio("sound/haimark.mp3");
var patricia = new Audio("sound/PATRICIA.mp3");
var cheeki = new Audio("sound/CheekiBreeki.mp3");

wtf.currentTime=0;
mada.currentTime=0;
healing.currentTime=0;
gay.currentTime=0;
omaewamu.currentTime=0;
depression.currentTime=0;
asteoporosis.currentTime=0;
die.currentTime=0;
slow.currentTime=0;
running.currentTime=0;
easy.currentTime=0;
nico.currentTime=0;
dance.currentTime=0;
computer.currentTime=0;
cena.currentTime=0;
rusure.currentTime=0;
bobtriggered.currentTime=0;
headshot.currentTime=0;
normies.currentTime=0;
minecraft.currentTime=0;
dead.currentTime=0;
mark.currentTime=0;
patricia.currentTime = 0;
cheeki.currentTime = 0;

function all(){
	wtf.play();
	mada.play();
	healing.play();
	gay.play();
	omaewamu.play();
	depression.play();
	asteoporosis.play();
	die.play();
	slow.play();
	running.play();
	easy.play();
	nico.play();
	dance.play();
	computer.play();
	cena.play();
	rusure.play();
	bobtriggered.play();
	headshot.play();
    normies.play();
    cheeki.play();
}